
##dockerfile para spark y python
FROM bitnami/spark:3.5.0
USER root
RUN apt-get update && apt-get install -y bash && pip install --no-cache-dir pyspark==3.5.0 plotly pandas && apt-get install -y procps



